 /$$$$$$$$ /$$   /$$  /$$$$$$  /$$      /$$ /$$$$$$$$
|_____ $$ | $$  | $$ /$$__  $$| $$$    /$$$| $$_____/
     /$$/ | $$  | $$| $$  \ $$| $$$$  /$$$$| $$      
    /$$/  | $$$$$$$$| $$  | $$| $$ $$/$$ $$| $$$$$   
   /$$/   | $$__  $$| $$  | $$| $$  $$$| $$| $$__/   
  /$$/    | $$  | $$| $$  | $$| $$\  $ | $$| $$      
 /$$$$$$$$| $$  | $$|  $$$$$$/| $$ \/  | $$| $$$$$$$$
|________/|__/  |__/ \______/ |__/     |__/|________/

________________________________________________________

ZHOME CONFIG FILE